modLoader = "javafml"
loaderVersion = "${forge_version_range}"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "energy_drinks_mod"
version = "${version}"
displayName = "Energy Drinks Mod"
authors = "deltadelete"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.energy_drinks_mod]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.energy_drinks_mod]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.energy_drinks_mod]]
modId = "architectury"
mandatory = true
versionRange = "${architectury_version_range}"
ordering = "AFTER"
side = "BOTH"